convertion_button_text = "Convert Numbers 🔘"
settings = "Settings ⚙️"
about = "About author 👨‍💻"
change_language_to_english = "English 🇺🇸"
change_language_to_uzbek = "Uzbek 🇺🇿"
back_to_main_menu = "Back to main menu 🔙"
back_to_previous_page = "Back to previous page ◀️"
you_on_main_menu = "You are on the main menu 🏠"

conversion_to_binary = "Conversion to binary 🔢"
conversion_to_octal = "Conversion to octal 🔢"
conversion_to_decimal = "Conversion to decimal 🔢"
conversion_to_hexadecimal = "Conversion to hexadecimal 🔢"
convertion_command_text = "<i>Choose a number system to convert:</i>"
conversion_type = "<b>Which conversion do you need?🔻</b>"

binary_to_octal = "Binary to Octal"
binary_to_decimal = "Binary to Decimal"
binary_to_hexadecimal = "Binary to Hexadecimal"
